In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as seabornns

In [2]:
df=pd.read_csv(r"C:\Users\rajan\Desktop\train.csv")

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.shape

(1460, 81)

In [5]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [6]:
df.shape

(1460, 81)

In [7]:
#selecting null columns > 20%
df_null_clm = df.isnull().sum()/df.shape[0]*100
df_null_clm[df_null_clm>20]

#dropping null columns > 20%
null_clm_list=df_null_clm[df_null_clm>20].index
# print(null_clm_list) # 6 columns
df=df.drop(columns=null_clm_list)

In [8]:
df_num_col=df.select_dtypes(include=['int','float'])
df_obj_col=df.select_dtypes(include=['object'])

In [9]:
df_num_col.shape

(1460, 38)

In [10]:
df_obj_col.shape

(1460, 37)

In [11]:
df_num_col['Id'].value_counts()

Id
1       1
982     1
980     1
979     1
978     1
       ..
485     1
484     1
483     1
482     1
1460    1
Name: count, Length: 1460, dtype: int64

In [12]:
df.drop('Id', axis=1, inplace=True) #No need of Id column in house price prediction

In [13]:
df.isnull().sum().sort_values(ascending=False).head(20)

LotFrontage     259
GarageYrBlt      81
GarageCond       81
GarageType       81
GarageFinish     81
GarageQual       81
BsmtFinType2     38
BsmtExposure     38
BsmtQual         37
BsmtFinType1     37
BsmtCond         37
MasVnrArea        8
Electrical        1
TotRmsAbvGrd      0
KitchenQual       0
KitchenAbvGr      0
BedroomAbvGr      0
HalfBath          0
FullBath          0
BsmtHalfBath      0
dtype: int64

In [14]:
garage_cols = ['GarageType','GarageFinish','GarageQual','GarageCond','GarageYrBlt']

df[garage_cols].isnull().sum()

GarageType      81
GarageFinish    81
GarageQual      81
GarageCond      81
GarageYrBlt     81
dtype: int64

In [15]:
cat_garage_cols = ['GarageType','GarageFinish','GarageQual','GarageCond']

for col in cat_garage_cols:
    df[col] = df[col].fillna('NoGarage')

df['GarageYrBlt'] = df['GarageYrBlt'].fillna(0)

#If we fill GarageType with the most common value like "Attached", we're telling the

In [16]:
df[garage_cols].isnull().sum()

GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
GarageYrBlt     0
dtype: int64

In [17]:
bsmt_cols = ['BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2']

df[bsmt_cols].isnull().sum()

BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinType2    38
dtype: int64

In [18]:
df[df['BsmtQual'].isnull()][['BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2']]

     BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2
17        NaN      NaN          NaN          NaN          NaN
39        NaN      NaN          NaN          NaN          NaN
90        NaN      NaN          NaN          NaN          NaN
102       NaN      NaN          NaN          NaN          NaN
156       NaN      NaN          NaN          NaN          NaN
182       NaN      NaN          NaN          NaN          NaN
259       NaN      NaN          NaN          NaN          NaN
342       NaN      NaN          NaN          NaN          NaN
362       NaN      NaN          NaN          NaN          NaN
371       NaN      NaN          NaN          NaN          NaN
392       NaN      NaN          NaN          NaN          NaN
520       NaN      NaN          NaN          NaN          NaN
532       NaN      NaN          NaN          NaN          NaN
533       NaN      NaN          NaN          NaN          NaN
553       NaN      NaN          NaN          NaN          NaN
646       NaN      NaN          NaN          NaN          NaN
705       NaN      NaN          NaN          NaN          NaN
736       NaN      NaN          NaN          NaN          NaN
749       NaN      NaN          NaN          NaN          NaN
778       NaN      NaN          NaN          NaN          NaN
868       NaN      NaN          NaN          NaN          NaN
894       NaN      NaN          NaN          NaN          NaN
897       NaN      NaN          NaN          NaN          NaN
984       NaN      NaN          NaN          NaN          NaN
1000      NaN      NaN          NaN          NaN          NaN
1011      NaN      NaN          NaN          NaN          NaN
1035      NaN      NaN          NaN          NaN          NaN
1045      NaN      NaN          NaN          NaN          NaN
1048      NaN      NaN          NaN          NaN          NaN
1049      NaN      NaN          NaN          NaN          NaN
1090      NaN      NaN          NaN          NaN          NaN
1179      NaN      NaN          NaN          NaN          NaN
1216      NaN      NaN          NaN          NaN          NaN
1218      NaN      NaN          NaN          NaN          NaN
1232      NaN      NaN          NaN          NaN          NaN
1321      NaN      NaN          NaN          NaN          NaN
1412      NaN      NaN          NaN          NaN          NaN

In [19]:
df[df['BsmtExposure'].isnull()][['BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2']]

     BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2
17        NaN      NaN          NaN          NaN          NaN
39        NaN      NaN          NaN          NaN          NaN
90        NaN      NaN          NaN          NaN          NaN
102       NaN      NaN          NaN          NaN          NaN
156       NaN      NaN          NaN          NaN          NaN
182       NaN      NaN          NaN          NaN          NaN
259       NaN      NaN          NaN          NaN          NaN
342       NaN      NaN          NaN          NaN          NaN
362       NaN      NaN          NaN          NaN          NaN
371       NaN      NaN          NaN          NaN          NaN
392       NaN      NaN          NaN          NaN          NaN
520       NaN      NaN          NaN          NaN          NaN
532       NaN      NaN          NaN          NaN          NaN
533       NaN      NaN          NaN          NaN          NaN
553       NaN      NaN          NaN          NaN          NaN
646       NaN      NaN          NaN          NaN          NaN
705       NaN      NaN          NaN          NaN          NaN
736       NaN      NaN          NaN          NaN          NaN
749       NaN      NaN          NaN          NaN          NaN
778       NaN      NaN          NaN          NaN          NaN
868       NaN      NaN          NaN          NaN          NaN
894       NaN      NaN          NaN          NaN          NaN
897       NaN      NaN          NaN          NaN          NaN
948        Gd       TA          NaN          Unf          Unf
984       NaN      NaN          NaN          NaN          NaN
1000      NaN      NaN          NaN          NaN          NaN
1011      NaN      NaN          NaN          NaN          NaN
1035      NaN      NaN          NaN          NaN          NaN
1045      NaN      NaN          NaN          NaN          NaN
1048      NaN      NaN          NaN          NaN          NaN
1049      NaN      NaN          NaN          NaN          NaN
1090      NaN      NaN          NaN          NaN          NaN
1179      NaN      NaN          NaN          NaN          NaN
1216      NaN      NaN          NaN          NaN          NaN
1218      NaN      NaN          NaN          NaN          NaN
1232      NaN      NaN          NaN          NaN          NaN
1321      NaN      NaN          NaN          NaN          NaN
1412      NaN      NaN          NaN          NaN          NaN

In [20]:
bsmt_cols = ['BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2']

for col in bsmt_cols:
    df[col] = df[col].fillna('NoBasement')

In [21]:
df[bsmt_cols].isnull().sum()

BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
dtype: int64

In [22]:
df.isnull().sum().sort_values(ascending=False).head(10)

LotFrontage     259
MasVnrArea        8
Electrical        1
HalfBath          0
Fireplaces        0
Functional        0
TotRmsAbvGrd      0
KitchenQual       0
KitchenAbvGr      0
BedroomAbvGr      0
dtype: int64

In [23]:
df['LotFrontage'].describe()

count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%        59.000000
50%        69.000000
75%        80.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [24]:
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].median())

In [25]:
df['LotFrontage'].isnull().sum()

np.int64(0)

In [26]:
df['MasVnrArea'].describe()

count    1452.000000
mean      103.685262
std       181.066207
min         0.000000
25%         0.000000
50%         0.000000
75%       166.000000
max      1600.000000
Name: MasVnrArea, dtype: float64

In [27]:
df['MasVnrArea'] = df['MasVnrArea'].fillna(df['MasVnrArea'].median())

In [28]:
df['MasVnrArea'].isnull().sum()

np.int64(0)

In [29]:
df['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [30]:
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])

In [31]:
df.isnull().sum().sum()

np.int64(0)

In [32]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [33]:
cat_cols = df.select_dtypes(include='object')

print("Number of categorical columns:", cat_cols.shape[1])
cat_cols.columns

Number of categorical columns: 37

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition'],
      dtype='object')

# ENCODING

In [34]:
df['MSZoning'].value_counts()

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

In [35]:
pd.get_dummies(df['MSZoning'], prefix='MSZoning')

      MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM
0                False        False        False         True        False
1                False        False        False         True        False
2                False        False        False         True        False
3                False        False        False         True        False
4                False        False        False         True        False
...                ...          ...          ...          ...          ...
1455             False        False        False         True        False
1456             False        False        False         True        False
1457             False        False        False         True        False
1458             False        False        False         True        False
1459             False        False        False         True        False

[1460 rows x 5 columns]

In [36]:
df= pd.get_dummies(df, columns=['MSZoning'], drop_first=True,dtype=int)

In [37]:
df

,MSSubClass,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,60,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,2,2008,WD,Normal,208500,0,0,1,0
1,20,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,...,0,5,2007,WD,Normal,181500,0,0,1,0
2,60,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,9,2008,WD,Normal,223500,0,0,1,0
3,70,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,...,0,2,2006,WD,Abnorml,140000,0,0,1,0
4,60,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,...,0,12,2008,WD,Normal,250000,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,...,0,8,2007,WD,Normal,175000,0,0,1,0
1456,20,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,...,0,2,2010,WD,Normal,210000,0,0,1,0
1457,70,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,...,2500,5,2010,WD,Normal,266500,0,0,1,0
1458,20,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,...,0,4,2010,WD,Normal,142125,0,0,1,0
1459,20,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,...,0,6,2008,WD,Normal,147500,0,0,1,0

In [38]:
df['Street'].value_counts()

Street
Pave    1454
Grvl       6
Name: count, dtype: int64

In [39]:
df['Street'] = df['Street'].map({
    'Grvl':0,
    'Pave':1
})

In [40]:
df['LotShape'].value_counts()

LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

In [41]:
lotshape_map = {
    'IR3': 1,
    'IR2': 2,
    'IR1': 3,
    'Reg': 4
}

df['LotShape'] = df['LotShape'].map(lotshape_map)

In [42]:
df['LandContour'].value_counts()

LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

In [43]:
df = pd.get_dummies(
    df,
    columns=['LandContour'],
    drop_first=True,
    dtype=int
)

# Problem

##### We will drop or not because (NoSeWa 1) has only one value

In [44]:
df['Utilities'].value_counts()

Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

In [45]:
df.drop('Utilities', axis=1, inplace=True)

In [46]:
df['LotConfig'].value_counts()

LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

In [47]:
df = pd.get_dummies(
    df,
    columns=['LotConfig'],
    drop_first=True,
    dtype=int
)

In [48]:
df['LandSlope'].value_counts()

LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

In [49]:
landslope_map = {
    'Sev': 1,
    'Mod': 2,
    'Gtl': 3
}

df['LandSlope'] = df['LandSlope'].map(landslope_map)

In [50]:
df['Neighborhood'].value_counts()

Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

In [51]:
df = pd.get_dummies(
    df,
    columns=['Neighborhood'],
    drop_first=True,
    dtype=int
)

In [52]:
df['Condition1'].value_counts()

Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

In [53]:
df = pd.get_dummies(
    df,
    columns=['Condition1'],
    drop_first=True,
    dtype=int
)

In [54]:
df['Condition2'].value_counts()

Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

In [55]:
df = pd.get_dummies(
    df,
    columns=['Condition2'],
    drop_first=True,
    dtype=int
)

In [56]:
df['BldgType'].value_counts()

BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

In [57]:
df = pd.get_dummies(
    df,
    columns=['BldgType'],
    drop_first=True,
    dtype=int
)

In [58]:
df['HouseStyle'].value_counts()

HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

In [59]:
df = pd.get_dummies(
    df,
    columns=['HouseStyle'],
    drop_first=True,
    dtype=int
)

In [60]:
df['RoofStyle'].value_counts()

RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

In [61]:
df = pd.get_dummies(
    df,
    columns=['RoofStyle'],
    drop_first=True,
    dtype=int
)

In [62]:
df['RoofMatl'].value_counts()

RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

In [63]:
df = pd.get_dummies(
    df,
    columns=['RoofMatl'],
    drop_first=True,
    dtype=int
)

In [64]:
df['Exterior1st'].value_counts()

Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

In [65]:
df = pd.get_dummies(
    df,
    columns=['Exterior1st'],
    drop_first=True,
    dtype=int
)

In [66]:
df['Exterior2nd'].value_counts()

Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

In [67]:
df = pd.get_dummies(
    df,
    columns=['Exterior2nd'],
    drop_first=True,
    dtype=int
)

In [68]:
df['ExterQual'].value_counts()

ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

In [69]:
quality_map = {
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['ExterQual'] = df['ExterQual'].map(quality_map)

In [70]:
df['ExterCond'] = df['ExterCond'].map(quality_map)

In [71]:
df = pd.get_dummies(
    df,
    columns=['Foundation'],
    drop_first=True,
    dtype=int
)

In [72]:
bsmtqual_map = {
    'NoBasement': 0,
    'Fa': 1,
    'TA': 2,
    'Gd': 3,
    'Ex': 4
}

df['BsmtQual'] = df['BsmtQual'].map(bsmtqual_map)

In [73]:
bsmtcond_map = {
    'NoBasement': 0,
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['BsmtCond'] = df['BsmtCond'].map(bsmtcond_map)

In [74]:
bsmt_exposure_map = {
    'NoBasement': 0,
    'No': 1,
    'Mn': 2,
    'Av': 3,
    'Gd': 4
}

df['BsmtExposure'] = df['BsmtExposure'].map(bsmt_exposure_map)

In [75]:
df['BsmtFinType1'].value_counts()

BsmtFinType1
Unf           430
GLQ           418
ALQ           220
BLQ           148
Rec           133
LwQ            74
NoBasement     37
Name: count, dtype: int64

In [76]:
bsmtfin_map = {
    'NoBasement': 0,
    'Unf': 1,
    'LwQ': 2,
    'Rec': 3,
    'BLQ': 4,
    'ALQ': 5,
    'GLQ': 6
}

df['BsmtFinType1'] = df['BsmtFinType1'].map(bsmtfin_map)
df['BsmtFinType2'] = df['BsmtFinType2'].map(bsmtfin_map)

In [77]:
df['Heating'].value_counts()

Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

In [78]:
df = pd.get_dummies(
    df,
    columns=['Heating'],
    drop_first=True,
    dtype=int
)

In [79]:
df['HeatingQC'].value_counts()

HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

In [80]:
quality_map = {
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['HeatingQC'] = df['HeatingQC'].map(quality_map)

In [81]:
df['CentralAir'].value_counts()

CentralAir
Y    1365
N      95
Name: count, dtype: int64

In [82]:
df['CentralAir'] = df['CentralAir'].map({
    'N': 0,
    'Y': 1
})

In [83]:
df['Electrical'].value_counts()

Electrical
SBrkr    1335
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [84]:
df = pd.get_dummies(
    df,
    columns=['Electrical'],
    drop_first=True,
    dtype=int
)

In [85]:
df['KitchenQual'].value_counts()

KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

In [86]:
quality_map = {
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['KitchenQual'] = df['KitchenQual'].map(quality_map)

In [87]:
df['Functional'].value_counts()

Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

In [88]:
functional_map = {
    'Sal': 1,
    'Sev': 2,
    'Maj2': 3,
    'Maj1': 4,
    'Mod': 5,
    'Min2': 6,
    'Min1': 7,
    'Typ': 8
}

df['Functional'] = df['Functional'].map(functional_map)

In [89]:
df['GarageType'].value_counts()

GarageType
Attchd      870
Detchd      387
BuiltIn      88
NoGarage     81
Basment      19
CarPort       9
2Types        6
Name: count, dtype: int64

In [90]:
df = pd.get_dummies(
    df,
    columns=['GarageType'],
    drop_first=True,
    dtype=int
)

In [91]:
df['GarageFinish'].value_counts()

GarageFinish
Unf         605
RFn         422
Fin         352
NoGarage     81
Name: count, dtype: int64

In [92]:
garage_finish_map = {
    'NoGarage': 0,
    'Unf': 1,
    'RFn': 2,
    'Fin': 3
}

df['GarageFinish'] = df['GarageFinish'].map(garage_finish_map)

In [93]:
df['GarageQual'].value_counts()

GarageQual
TA          1311
NoGarage      81
Fa            48
Gd            14
Ex             3
Po             3
Name: count, dtype: int64

In [94]:
garage_quality_map = {
    'NoGarage': 0,
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['GarageQual'] = df['GarageQual'].map(garage_quality_map)

In [95]:
df['GarageCond'].value_counts()

GarageCond
TA          1326
NoGarage      81
Fa            35
Gd             9
Po             7
Ex             2
Name: count, dtype: int64

In [96]:
garage_quality_map = {
    'NoGarage': 0,
    'Po': 1,
    'Fa': 2,
    'TA': 3,
    'Gd': 4,
    'Ex': 5
}

df['GarageCond'] = df['GarageCond'].map(garage_quality_map)

In [97]:
df['PavedDrive'].value_counts()

PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

In [98]:
paved_drive_map = {
    'N': 0,
    'P': 1,
    'Y': 2
}

df['PavedDrive'] = df['PavedDrive'].map(paved_drive_map)

In [99]:
df['SaleType'].value_counts()

SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

In [100]:
df['SaleCondition'].value_counts()

SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

In [101]:
df = pd.get_dummies(
    df,
    columns=['SaleType', 'SaleCondition'],
    drop_first=True,
    dtype=int
)

# verify encoding

In [102]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [103]:
df.isnull().sum().sort_values(ascending=False).head(10)

MSSubClass             0
Exterior1st_BrkFace    0
RoofMatl_CompShg       0
RoofMatl_Membran       0
RoofMatl_Metal         0
RoofMatl_Roll          0
RoofMatl_Tar&Grv       0
RoofMatl_WdShake       0
RoofMatl_WdShngl       0
Exterior1st_AsphShn    0
dtype: int64

In [104]:
df.shape

(1460, 190)

In [105]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

In [106]:
print(df.dtypes.value_counts())

int64      187
float64      3
Name: count, dtype: int64

In [107]:
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [108]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Scaling

In [109]:
from sklearn.preprocessing import StandardScaler

In [110]:
scaler = StandardScaler()

In [111]:
X_train_scaled = scaler.fit_transform(X_train)

In [112]:
print(type(X_train_scaled))

<class 'numpy.ndarray'>

In [113]:
print(X_train_scaled.shape)

(1168, 189)

In [114]:
X_test_scaled = scaler.transform(X_test)

# Model Selection

In [115]:
from sklearn.linear_model import LinearRegression

In [116]:
lr = LinearRegression()

In [117]:
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [118]:
y_pred = lr.predict(X_test_scaled)

In [119]:
from sklearn.metrics import r2_score

print(r2_score(y_test, y_pred))

0.6810296465824539

In [120]:
print("Train R2:", lr.score(X_train_scaled, y_train))
print("Test R2 :", lr.score(X_test_scaled, y_test))

Train R2: 0.919187423257249
Test R2 : 0.6810296465824539

In [121]:
from sklearn.linear_model import Ridge

In [122]:
ridge = Ridge(alpha=1.0)

In [123]:
ridge.fit(X_train_scaled, y_train)

Ridge()

In [124]:
y_pred_ridge = ridge.predict(X_test_scaled)

In [125]:
print("Train R2:", ridge.score(X_train_scaled, y_train))
print("Test R2 :", ridge.score(X_test_scaled, y_test))

Train R2: 0.9190483385870031
Test R2 : 0.7086115546447719